In [1]:
import pandas as pd
import json

In [3]:
# Загружаем json
with open(r'C:\PycharmProjects\ndv_parcing\!changing_haracteristik_dictionary\projects.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

In [18]:
with open(r"C:\PycharmProjects\ndv_parcing\!haracteristik_dictionary\projects.json", "r", encoding="utf-8") as f:
    data2 = json.load(f)

In [19]:
project_map = {}

for project in data2.values():
    project_id = project.get("id")
    if project_id:
        project_map[project_id] = {
            "Округ": project.get("Округ"),
            "Район": project.get("Район"),
            "Класс": project.get("Класс"),
        }

In [2]:
df = pd.read_excel(r'C:\PycharmProjects\ndv_parcing\НашДомРФ\2026-07-27\НашДомРФ_глубже_080626_add.xlsx')

In [16]:
df["id"] = (
    df["ID дом.рф"]
    .astype("Int64")      # если есть NaN
    .astype(str)
    .map(id_map)
)

In [12]:
# Создаем словарь соответствий
id_map = {}

for project in data.values():
    for house in project.values():
        domrf_id = house.get("ID дом.рф")
        if domrf_id:
            id_map[domrf_id] = house.get("id")   # или без int, если в df строка

# Добавляем столбец в DataFrame
id_map[domrf_id] = house.get("id")

In [17]:
df

,ID дом.рф,Название проекта,Застройщик,Группа компаний,Статус,Дата публикации проекта,Ввод в эксплуатацию,Выдача ключей,Распроданность квартир,Остаток квартир,...,Количество мест в паркинге,Гостевые места на придомовой территории,Гостевые места вне придомовой территории,Наличие пандуса,Наличие понижающих площадок,Количество инвалидных подъемников,Количество подъездов,Количество пассажирских лифтов,Количество грузовых и грузопассажирских лифтов,id
0,42848,Жилой комплекс Воксхолл,АО СЗ КОМПЛЕКТ,Эталон,Сдан,28.09.2021,2 кв 2026,30.07.2026,0.72,44.0,...,206,36,Нет,Нет,Есть,Нет,3,10,Нет,5641
1,43864,Glorax Premium Белорусская,ООО СЗ КАССИОПЕЯ,GloraX,Сдан,30.11.2021,2 кв 2025,30.06.2025,NaN,NaN,...,127,Нет,Нет,Нет,Нет,Нет,-,3,3,4205
2,54294,Шолохово малоэтажный жилой комплекс,ООО СЗ НОВОТУТИНКИ,РосЕвроСити,Строится,15.09.2023,3 кв 2026,28.02.2027,0.39,78.0,...,Нет,20,25,Есть,Есть,Нет,7,Нет,Нет,1782
3,62266,"МИРАПОЛИС, КВАРТАЛ МИРАПОЛИС",АО СЗ ТПУ РОСТОКИНО,ОСНОВА,Строится,24.09.2024,4 кв 2027,16.06.2028,NaN,NaN,...,Нет,593,Нет,Нет,Есть,Нет,-,16,Нет,nan
4,57805,ЖК 1-й Донской,ООО СЗ СТОЛИЦА ЮГА,ФСК,Строится,14.02.2024,1 кв 2027,30.09.2027,0.48,407.0,...,138,8,72,Нет,Есть,Нет,3,6,3,6921
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1477,27247,"Жилой комплекс""Люблинский парк""",ООО СЗ ЛЮБЛИНО ДЕВЕЛОПМЕНТ,ПИК,Строится,31.05.2019,3 кв 2028,25.10.2028,0.16,240.0,...,Нет,Нет,116,Есть,Есть,Нет,1,4,4,4429
1478,71246,"ЖК ""Гранель Аникеевский""",ООО СЗ ГРАНЕЛЬ ГОРОД,Гранель,Строится,06.04.2026,2 кв 2028,31.12.2028,NaN,NaN,...,Нет,14,9,Есть,Есть,Нет,8,Нет,8,nan
1479,54528,"Жилой комплекс ""Кутузовский квартал""",АО СЗ МОНЕТЧИК,ПИК,Сдан,28.09.2023,3 кв 2026,31.07.2026,0.81,107.0,...,71,33,83,Нет,Есть,Нет,2,Нет,7,7684
1480,36169,"Жилой район «Южная Битца», Жилой комплекс «Южн...",ООО СЗ ВОСТОК СТОЛИЦЫ,ФСК,Сдан,23.06.2020,4 кв 2021,30.06.2022,0.63,551.0,...,Нет,52,Нет,Есть,Есть,Нет,13,8,19,4622
1481,47447,Новые Ватутинки,ООО СЗ СТРОЙКОМ 1,Стройком,Сдан,05.08.2022,3 кв 2025,30.12.2025,0.92,116.0,...,675,147,313,Есть,Есть,Нет,21,10,21,6164

In [14]:
id_map

{'nan': 'nan',
 '62732': '6921',
 '57805': '6921',
 '56862': '6921',
 '51450': '6921',
 '51452': '6921',
 '63646': '7268',
 '56212': '7268',
 '42833': '5642',
 '42834': '5642',
 '44411': '5642',
 '44969': '5642',
 '47579': '5642',
 '37322': '5043',
 '37324': '5043',
 '44603': '5043',
 '40687': '5043',
 '40688': '5043',
 '62843': '7622',
 '62055': '7622',
 '60896': '7622',
 '60421': '7409',
 '62547': '7409',
 '63222': '7409',
 '69086': '7409',
 '70084': 'nan',
 '56725': '6922',
 '58301': '6922',
 '53370': '6922',
 '51881': '6922',
 '61323': 'nan',
 '51818': '6923',
 '51623': '6923',
 '51741': '6923',
 '61088': '6923',
 '53382': '6923',
 '64704': '6923',
 '70027': '6923',
 '56157': '7269',
 '56514': '7269',
 '62247': '7269',
 '69153': '7269',
 '58644': '7464',
 '63629': '7464',
 '63594': '7464',
 '56028': '1281',
 '55109': '7243',
 '39566': '4945',
 '39567': '4945',
 '38163': '5095',
 '25870': '5538',
 '45298': '5806',
 '36234': 'nan',
 '41606': '5553',
 '58524': '7462',
 '70095': 'nan',
 '55218': '4511',
 '59759': '7592',
 '19620': '4264',
 '45473': '5813',
 '46060': '2088',
 '51928': '4962',
 '64568': '4962',
 '43322': '4962',
 '55432': '4962',
 '69273': '4962',
 '57752': '7393',
 '67615': '7393',
 '71089': '7393',
 '42764': '5640',
 '48352': '6283',
 '7708': '4780',
 '57838': '7401',
 '69149': '8881',
 '64096': '7594',
 '41549': '5114',
 '53464': '7067',
 '37487': '5057',
 '62125': '6763',
 '50651': '6763',
 '39040': '5143',
 '45276': 'nan',
 '58201': '7419',
 '57919': '7400',
 '39481': '4298',
 '32274': '2018',
 '58132': '6937',
 '58133': '6937',
 '43253': '5691',
 '51237': '6787',
 '45604': '4551',
 '61266': '7053',
 '43864': '4205',
 '27921': '2038',
 '27917': '2038',
 '27918': '2038',
 '27916': '2038',
 '27919': '2038',
 '27923': '2038',
 '27920': '2038',
 '37004': '5023',
 '55198': '5144',
 '43134': '5144',
 '46826': '4795',
 '54521': '4795',
 '64808': '8541',
 '27927': '4550',
 '23185': '4550',
 '23186': '4550',
 '27926': '4550',
 '27928': '4550',
 '53748': '7057',
 '47486': '6170',
 '56687': '7258',
 '42714': '5633',
 '57465': '7298',
 '43199': '5131',
 '49564': '6627',
 '50740': '6748',
 '67276': '8731',
 '59370': '7589',
 '50325': '7616',
 '50327': '7616',
 '50326': '7616',
 '54102': '5639',
 '61276': '5639',
 '45205': '5639',
 '43667': '5639',
 '43668': '5639',
 '54984': '7239',
 '61714': '4818',
 '39041': '4818',
 '39042': '4818',
 '45197': '5032',
 '45199': '5032',
 '45203': '5032',
 '45204': '5032',
 '53635': '6108',
 '46601': '6108',
 '53661': '5811',
 '64983': '5811',
 '64985': '5811',
 '55312': '5811',
 '45519': '5811',
 '52870': '6977',
 '46310': '6085',
 '54281': '4407',
 '40964': '4407',
 '44841': '5765',
 '25802': '4637',
 '25801': '4637',
 '48767': '6310',
 '34180': '4508',
 '40279': '5108',
 '42009': '5602',
 '65465': '5804',
 '45349': '5804',
 '62556': 'nan',
 '62557': 'nan',
 '66793': '8700',
 '54454': '7083',
 '66240': '7083',
 '45192': '5794',
 '25260': '1920',
 '55387': '7255',
 '58150': '7255',
 '68245': '8703',
 '48243': '6213',
 '59212': '7567',
 '49360': '6097',
 '62590': '7767',
 '22945': '4563',
 '45970': 'nan',
 '45969': '5927',
 '47464': '1702',
 '43779': '1702',
 '50682': '1702',
 '38022': '1702',
 '30979': '4668',
 '30980': '4668',
 '30981': '4668',
 '26835': '4799',
 '42908': '5183',
 '61562': '7698',
 '62614': '7698',
 '59685': '7600',
 '59686': '7600',
 '45414': '5129',
 '57194': '5129',
 '51376': '5129',
 '46514': '5129',
 '48723': '5129',
 '48994': '5129',
 '64325': 'nan',
 '64324': 'nan',
 '61046': 'nan',
 '59391': 'nan',
 '66527': 'nan',
 '67498': 'nan',
 '66997': 'nan',
 '65825': 'nan',
 '57362': '7261',
 '44330': '5701',
 '44331': '5701',
 '44332': '5701',
 '56264': '5722',
 '56265': '5722',
 '44142': '5722',
 '29997': '647',
 '29999': '647',
 '39321': '2006',
 '47436': '2006',
 '5209': '2006',
 '31015': '2006',
 '5210': '2006',
 '35358': '4838',
 '53747': '5133',
 '41182': '1693',
 '65338': '8593',
 '62103': '7696',
 '32319': '4718',
 '32318': '4718',
 '66661': '8603',
 '50268': '6619',
 '52082': '5094',
 '42772': '5094',
 '46127': '5094',
 '46066': '5094',
 '56210': '7281',
 '49580': '6629',
 '50150': '4840',
 '50152': '4840',
 '50153': '4840',
 '50154': '4840',
 '53658': '7055',
 '66013': '8610',
 '65944': '8609',
 '45822': '5830',
 '65141': '8552',
 '62789': '7776',
 '56269': '6741',
 '56270': '6741',
 '50049': '6741',
 '60872': '7617',
 '67620': '7617',
 '59598': '5148',
 '39483': '5148',
 '39482': '5148',
 '39485': '5148',
 '23773': '4556',
 '58300': '7422',
 '64840': '4990',
 '64841': '4990',
 '60564': '7664',
 '42848': '5641',
 '42849': '5641',
 '56623': '5734',
 '44140': '5734',
 '48298': '6226',
 '36567': '4717',
 '29438': '4717',
 '43820': '5714',
 '45596': '5829',
 '55395': 'nan',
 '64921': '8539',
 '64430': '8257',
 '12246': 'nan',
 '63966': 'nan',
 '49325': '6427',
 '66746': '8164',
 '61294': '4741',
 '51218': '4741',
 '64596': '6198',
 '48581': '4747',
 '48578': '4747',
 '49494': '4747',
 '48577': '4747',
 '48580': '4747',
 '49495': '4747',
 '61842': '7571',
 '61843': '7571',
 '72362': '7571',
 '51308': '6924',
 '66710': '4960',
 '46925': '4960',
 '52220': '6956',
 '52221': '6956',
 '52222': '6956',
 '52223': '6956',
 '52224': '6956',
 '62793': '5752',
 '62839': '5752',
 '62840': '5752',
 '62841': '5752',
 '68181': '5752',
 '69387': '5752',
 '70395': 'nan',
 '48353': '6286',
 '38367': '5103',
 '65496': 'nan',
 '65994': 'nan',
 '70009': '8961',
 '57750': '1003',
 '36920': '5019',
 '43879': '5708',
 '43707': '5708',
 '60548': '7618',
 '37984': '5085',
 '47431': '5085',
 '67205': '8730',
 '24926': '4214',
 '48706': '5194',
 '62293': '7759',
 '64065': '4418',
 '16222': '4418',
 '16128': '4418',
 '16127': '4418',
 '29553': '4418',
 '70690': '4418',
 '54218': '7072',
 '54219': '7072',
 '54220': '7072',
 '54723': '7072',
 '54724': '7072',
 '54725': '7072',
 '63895': '1177',
 '63896': '1177',
 '26141': '4229',
 '35466': '4304',
 '35467': 'nan',
 '35468': 'nan',
 '65192': '8174',
 '37646': '5071',
 '58187': '5071',
 '54449': '7074',
 '54450': '7074',
 '54313': '7074',
 '54314': '7074',
 '54315': '7074',
 '54316': '7074',
 '37647': '4985',
 '52350': '4985',
 '53897': '4985',
 '24222': '4294',
 '31626': '4719',
 '62896': '7771',
 '56394': '4505',
 '56214': '4505',
 '70382': 'nan',
 '70409': 'nan',
 '55205': '4510',
 '49932': '4510',
 '49933': '4510',
 '35601': '4847',
 '37418': '4847',
 '37417': '4847',
 '64462': '8258',
 '50291': '6751',
 '65460': '8597',
 '48278': '6190',
 '51310': '6190',
 '47770': '6190',
 '55874': '6190',
 '53516': '6190',
 '55224': '6190',
 '56356': '6190',
 '57179': '5020',
 '57291': '5020',
 '59934': '5020',
 '44510': '5020',
 '46220': '5020',
 '44069': '1009',
 '46532': '1009',
 '46536': '1009',
 '46539': '1009',
 '46537': '1009',
 '48808': '6313',
 '45185': '5789',
 '66242': '5789',
 '45184': '5789',
 '34307': '4776',
 '1688': '2112',
 '1689': '2112',
 '11446': '2112',
 '59146': '4836',
 '59147': '4836',
 '49696': '1993',
 '57918': '7397',
 '30231': '683',
 '30640': '683',
 '30090': '683',
 '61312': '4812',
 '55781': '4812',
 '34549': '4812',
 '54355': '4812',
 '54356': '4812',
 '60790': '7669',
 '56031': '8520',
 '56036': '8520',
 '64932': '1012',
 '64933': '1012',
 '67679': '1012',
 '52949': '1012',
 '45081': '1012',
 '45082': '1012',
 '52950': '1012',
 '69251': 'nan',
 '69252': 'nan',
 '48522': '1013',
 '61267': 'nan',
 '59184': '7279',
 '3373': '4204',
 '46540': '5046',
 '46118': '5046',
 '50307': '1580',
 '53175': '1637',
 '52790': '6974',
 '64595': '8515',
 '69718': '8515',
 '12092': '4402',
 '63048': 'nan',
 '63049': 'nan',
 '63051': 'nan',
 '63052': 'nan',
 '63053': 'nan',
 '63055': 'nan',
 '63056': 'nan',
 '63050': 'nan',
 '63054': 'nan',
 '63047': 'nan',
 '55165': '5610',
 '55166': '5610',
 '55594': '5610',
 '55595': '5610',
 '70179': 'nan',
 '70180': 'nan',
 '25173': '4543',
 '25172': '4543',
 '69987': 'nan',
 '69988': 'nan',
 '51560': '6925',
 '56234': '6925',
 '70100': '6925',
 '69199': 'nan',
 '23196': '4419',
 '19561': '1545',
 '66212': '7059',
 '53889': '7059',
 '44775': '1264',
 '44777': '1264',
 '55433': '7251',
 '59683': '7251',
 '56693': '6284',
 '67099': '6284',
 '48389': '6284',
 '48946': '6284',
 '52641': '6284',
 '53150': '6284',
 '56694': '6284',
 '64768': '6152',
 '47112': 'nan',
 '49226': '6152',
 '28315': '4640',
 '54680': '6212',
 '48124': '6212',
 '48125': '6212',
 '55142': '7082',
 '59595': '7593',
 '7910': '4360',
 '46510': '6095',
 '53713': '7056',
 '60533': '7621',
 '59440': '7587',
 '60712': '7280',
 '51432': '6920',
 '51091': '7071',
 '52381': '6962',
 '59328': '7591',
 '66274': 'nan',
 '69377': 'nan',
 '69374': 'nan',
 '69376': 'nan',
 '51566': '6733',
 '51567': '6733',
 '45882': '4832',
 '25400': '4564',
 '25407': '4564',
 '25405': '4564',
 '25993': '4564',
 '25372': '4564',
 '57962': '4447',
 '57963': '4447',
 '53790': '6948',
 '38823': '4770',
 '69291': '8834',
 '68887': '8834',
 '57447': '7284',
 '57448': '7284',
 '43955': '5650',
 '47685': '5650',
 '43153': '5650',
 '54864': '5650',
 '55633': '5650',
 '56965': '5650',
 '71445': 'nan',
 '58854': 'nan',
 '51002': '6944',
 '58855': '6944',
 '71440': 'nan',
 '64520': '5139',
 '66869': 'nan',
 '40325': '5139',
 '40855': '5139',
 '48981': '4405',
 '59326': '7588',
 '48583': '5101',
 '40373': '5101',
 '60457': '5101',
 '57906': '7403',
 '58597': '7465',
 '58598': '7465',
 '56750': '5721',
 '61588': '5721',
 '66801': '5721',
 '70846': '5721',
 '67146': 'nan',
 '59756': '1792',
 '54931': '1792',
 '20033': '4582',
 '53142': '7037',
 '47907': '2067',
 '45977': '5922',
 '65419': '5750',
 '51416': '5750',
 '63900': '1919',
 '63789': '1919',
 '63754': '1919',
 '63787': '1919',
 '63901': '1919',
 '63755': '1919',
 '64805': '1919',
 '64806': '1919',
 '64807': '1919',
 '55115': '1919',
 '56436': '1919',
 '55116': '1919',
 '52142': '1919',
 '72225': '1919',
 '68618': '1779',
 '21486': '1779',
 '40685': '1779',
 '27752': '1779',
 '37541': '1779',
 '58588': '7475',
 '52567': '6970',
 '65452': '6970',
 '39827': '5119',
 '44125': '5735',
 '42441': '5629',
 '25663': '1976',
 '63948': '5728',
 '63949': '5728',
 '44387': 'nan',
 '37859': '4778',
 '49357': '6428',
 '49356': '6428',
 '40465': '2029',
 '57881': '1752',
 '57882': '1752',
 '57883': '1752',
 '57884': '1752',
 '57885': '1752',
 '44093': '1752',
 '44095': '1752',
 '60525': '1789',
 '60526': '1789',
 '60527': '1789',
 '54036': '6154',
 '54037': '6154',
 '54038': '6154',
 '54039': '6154',
 '60229': '7063',
 '53577': '7063',
 '56672': '7063',
 '56673': '7063',
 '56674': '7063',
 '63957': '4947',
 '66910': '4947',
 '65561': '4947',
 '51315': '4947',
 '43451': '4947',
 '43836': '4947',
 '52788': '4947',
 '59656': '4947',
 '59789': '4947',
 '62749': '4947',
 '69508': '4947',
 '54791': '4947',
 '56266': '7285',
 '59507': '7285',
 '55760': '6976',
 '53581': '6976',
 '50270': '6752',
 '58299': '6752',
 '58298': '6752',
 '57478': '6752',
 '50269': '6752',
 '53618': '6752',
 '69524': '6293',
 '48535': '6293',
 '49925': '6293',
 '53066': '6293',
 '58312': '7423',
 '56715': '6777',
 '67209': '6777',
 '50975': '6777',
 '50976': '6777',
 '54577': '7232',
 '58281': '7232',
 '66931': 'nan',
 '58168': '7414',
 '67723': '6769',
 '55686': '6769',
 '55687': '6769',
 '46091': '5925',
 '48184': '5925',
 '49291': '6320',
 '49099': '6320',
 '57817': '7399',
 '51894': '6943',
 '59505': '6943',
 '51949': '6943',
 '60486': '7253',
 '60532': '7253',
 '55393': '7253',
 '36569': '4988',
 '36570': '4988',
 '47909': '4988',
 '48257': '6227',
 '48258': '6227',
 '48259': '6227',
 '48260': '6227',
 '68396': 'nan',
 '56224': '7583',
 '30108': 'nan',
 '67659': 'nan',
 '40640': '5120',
 '62503': '7765',
 '69179': '8827',
 '68196': '8805',
 '68198': '8805',
 '46429': '5145',
 '28978': '4771',
 '62401': '7760',
 '48693': '1969',
 '48694': '1969',
 '59538': 'nan',
 '56296': '7254',
 '58464': '4987',
 '65371': 'nan',
 '65372': 'nan',
 '65370': 'nan',
 '61221': '5035',
 '38361': '5035',
 '38364': '5035',
 '28075': '4454',
 '28076': '4454',
 '28077': '4454',
 '28078': '4454',
 '56102': '7277',
 '50148': '4643',
 '65723': '8525',
 '54528': '7684',
 '10884': '1971',
 '66363': 'nan',
 '58482': '7418',
 '58481': '7418',
 '58480': '7418',
 '58483': '7418',
 '58479': '7418',
 '62498': '7761',
 '66480': 'nan',
 '56795': '4559',
 '56792': '4559',
 '70939': 'nan',
 '70938': 'nan',
 '66132': '5631',
 '42662': 'nan',
 '69431': '8888',
 '38951': '5141',
 '60011': '5916',
 '45908': '5916',
 '54862': '5916',
 '54860': '5916',
 '43264': '2107',
 '43267': '2107',
 '61985': '7693',
 '27247': '4429',
 '27248': '4429',
 '27250': '4429',
 '27243': '4429',
 '52063': '4429',
 '53669': '7062',
 '31042': '4694',
 '61674': 'nan',
 '61676': 'nan',
 '61675': 'nan',
 '24534': '4491',
 '24535': '4491',
 '47076': 'nan',
 '63962': '8180',
 '59144': '7568',
 '63924': '8162',
 '64446': '8259',
 '65834': '7609',
 '62494': '7609',
 '65703': '7609',
 '63354': '7609',
 '63359': '7609',
 '65833': '7609',
 '70548': 'nan',
 '61521': '5600',
 '63603': '5600',
 '46019': '5600',
 '46021': '5600',
 '46020': '5600',
 '41967': '5600',
 '21857': 'nan',
 '70594': 'nan',
 '47273': '4514',
 '34119': '4514',
 '34120': '4514',
 '39416': '4514',
 '41475': '5552',
 '41476': '5552',
 '62998': '7774',
 '62265': '6311',
 '62266': 'nan',
 '68929': 'nan',
 '48736': '5652',
 '1286': '5652',
 '20461': '4430',
 '68221': '8811',
 '68222': '8811',
 '64219': '5160',
 '46432': '5160',
 '39825': '5160',
 '69977': '5160',
 '59213': '5124',
 '63659': '5124',
 '44165': '5124',
 '69549': '5124',
 '44964': '1353',
 '44676': '1353',
 '44675': '1353',
 '44965': '1353',
 '44893': '1353',
 '44894': '1353',
 '48466': '5805',
 '45318': '5805',
 '54505': '5805',
 '54541': '5805',
 '56071': '5805',
 '57792': 'nan',
 '53988': '6327',
 '51053': '6327',
 '59506': '7575',
 '37024': '5031',
 '60880': '7667',
 '58243': '7417',
 '70610': 'nan',
 '65525': '8591',
 '65513': '8591',
 '70050': '8591',
 '70051': '8591',
 '70052': '8591',
 '71066': '8591',
 '71062': '8591',
 '71745': '8591',
 '56544': '5104',
 '38377': '5104',
 '46173': '5104',
 '46174': '5104',
 '43749': '5104',
 '40410': '5104',
 '55701': '5104',
 '58714': '6228',
 '58713': '6228',
 '48266': '6228',
 '45826': '4635',
 '49777': '4635',
 '34125': '4635',
 '41018': '5187',
 '66234': '8650',
 '22643': '4520',
 '22644': '4520',
 '68821': 'nan',
 '68822': 'nan',
 '8333': 'nan',
 '68781': 'nan',
 '59157': '7566',
 '60273': '7240',
 '55103': '7240',
 '59150': '5697',
 '49606': '5697',
 '43313': 'nan',
 '43314': 'nan',
 '59365': '7289',
 '59367': '7289',
 '64123': '7289',
 '64126': 'nan',
 '67314': '7289',
 '66547': '7289',
 '56531': '7289',
 '56533': '7289',
 '57119': '7289',
 '54383': '2096',
 '54348': '2096',
 '54377': '2096',
 '65023': '2096',
 '71108': '2096',
 '66399': '1692',
 '66400': '1692',
 '20977': '1692',
 '62044': '7695',
 '62089': '7695',
 '71282': '7695',
 '71283': '7695',
 '51415': '4710',
 '31981': '4710',
 '45498': '4710',
 '50695': '4759',
 '59896': '4759',
 '59629': '4759',
 '59628': '4759',
 '51388': '4759',
 '69275': '8883',
 '67732': '5060',
 '67731': '5060',
 '67735': '5060',
 '67733': '5060',
 '47065': '5060',
 '47061': '5060',
 '47067': '5060',
 '47066': '5060',
 '47059': '5060',
 '47063': '5060',
 '37556': '5060',
 '37555': '5060',
 '37554': '5060',
 '67730': '5060',
 '67728': '5060',
 '50516': '1735',
 '50517': '1735',
 '50764': '1735',
 '43633': '1735',
 '43699': '1735',
 '43359': '1735',
 '50519': '1735',
 '42557': '5627',
 '50893': '6760',
 '50890': '6760',
 '50891': '6760',
 '50581': '6760',
 '50493': '6760',
 '50494': '6760',
 '56898': '6760',
 '56899': '6760',
 '56932': '6760',
 '56933': '6760',
 '48613': '5112',
 '50234': '5112',
 '50235': '5112',
 '50236': '5112',
 '50237': '5112',
 '50238': '5112',
 '53411': '5112',
 '53412': '5112',
 '53413': '5112',
 '56944': '5112',
 '56945': '5112',
 '56949': '5112',
 '56950': '5112',
 '56951': '5112',
 '51503': '6927',
 '47012': '1360',
 '47013': '1360',
 '40359': '1360',
 '47336': '1360',
 '47337': '1360',
 '47338': '1360',
 '47502': '1088',
 '47503': '1088',
 '45219': '1088',
 '44354': '1088',
 '44356': '1088',
 '47625': '1081',
 '56062': '4814',
 '56063': '4814',
 '68174': '4814',
 '68276': 'nan',
 '59237': '6164',
 '44166': '6164',
 '47447': '6164',
 '30782': '1969',
 '30783': '1969',
 '37714': '1969',
 '37715': '1969',
 '41764': '1969',
 '68200': '1039',
 '25682': '4426',
 '62069': '7689',
 '63015': '7689',
 '63020': 'nan',
 '69088': '1117',
 '61251': '1602',
 '37819': '1602',
 '37820': '1602',
 '40380': '1602',
 '40381': '1602',
 '51274': '1602',
 '38388': '5113',
 '42855': '5113',
 '51766': '6940',
 '51572': 'nan',
 '50442': '1133',
 '47154': '1133',
 '65533': '4680',
 '28577': '4680',
 '44483': '4680',
 '28576': '4680',
 '32325': '4680',
 '32326': '4680',
 '44481': '4680',
 '44482': '4680',
 '61484': '8165',
 '64641': '8165',
 '67384': '1706',
 '46238': '6081',
 '61654': '7680',
 '58289': '7690',
 '53542': '7065',
 '53543': '7065',
 '53541': '7065',
 '47114': '6153',
 '55028': '1355',
 '68513': 'nan',
 '29419': '1901',
 '29414': '1901',
 '29420': '1901',
 '29421': '1901',
 '68806': '8832',
 '56304': '4368',
 '56305': '4368',
 '56306': '4368',
 '56307': '4368',
 '49609': '4368',
 '49610': '4368',
 '49608': '4368',
 '12328': '4368',
 '47132': '4368',
 '55644': '5126',
 '62038': '5126',
 '62039': '5126',
 '66520': '5126',
 '67396': '5126',
 '69675': '5126',
 '41982': '5126',
 '44393': 'nan',
 '58828': 'nan',
 '68122': '4980',
 '62137': '4980',
 '62138': '4980',
 '64204': '4980',
 '64205': '4980',
 '54533': '7081',
 '62728': '2094',
 '65114': '2094',
 '19430': '2094',
 '46638': '2094',
 '56494': '2094',
 '64620': '8516',
 '64622': '8516',
 '64621': '8516',
 '64627': '8516',
 '68269': 'nan',
 '43381': '2109',
 '39214': '2109',
 '39215': '2109',
 '1838': '2109',
 '24702': '2109',
 '40363': '2109',
 '46292': '6082',
 '69663': '6650',
 '64244': '8172',
 '67424': '8172',
 '46357': '6096',
 '50218': '6096',
 '64029': '1982',
 '64073': '1982',
 ...}

In [15]:
print(df["ID дом.рф"].dtype)
print(type(next(iter(id_map.keys()))))

int64
<class 'str'>

In [21]:
df = df.join(df["id"].map(project_map).apply(pd.Series))

In [22]:
df

,ID дом.рф,Название проекта,Застройщик,Группа компаний,Статус,Дата публикации проекта,Ввод в эксплуатацию,Выдача ключей,Распроданность квартир,Остаток квартир,...,Наличие понижающих площадок,Количество инвалидных подъемников,Количество подъездов,Количество пассажирских лифтов,Количество грузовых и грузопассажирских лифтов,id,Округ,Район,Класс,0
0,42848,Жилой комплекс Воксхолл,АО СЗ КОМПЛЕКТ,Эталон,Сдан,28.09.2021,2 кв 2026,30.07.2026,0.72,44.0,...,Есть,Нет,3,10,Нет,5641,ЦАО,Замоскворечье,бизнес,NaN
1,43864,Glorax Premium Белорусская,ООО СЗ КАССИОПЕЯ,GloraX,Сдан,30.11.2021,2 кв 2025,30.06.2025,NaN,NaN,...,Нет,Нет,-,3,3,4205,САО,Беговой,премиум,NaN
2,54294,Шолохово малоэтажный жилой комплекс,ООО СЗ НОВОТУТИНКИ,РосЕвроСити,Строится,15.09.2023,3 кв 2026,28.02.2027,0.39,78.0,...,Есть,Нет,7,Нет,Нет,1782,Мытищинский,Федоскино,комфорт,NaN
3,62266,"МИРАПОЛИС, КВАРТАЛ МИРАПОЛИС",АО СЗ ТПУ РОСТОКИНО,ОСНОВА,Строится,24.09.2024,4 кв 2027,16.06.2028,NaN,NaN,...,Есть,Нет,-,16,Нет,nan,ТАО,Первомайское,бизнес,NaN
4,57805,ЖК 1-й Донской,ООО СЗ СТОЛИЦА ЮГА,ФСК,Строится,14.02.2024,1 кв 2027,30.09.2027,0.48,407.0,...,Есть,Нет,3,6,3,6921,Ленинский,Сапроново,комфорт,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1477,27247,"Жилой комплекс""Люблинский парк""",ООО СЗ ЛЮБЛИНО ДЕВЕЛОПМЕНТ,ПИК,Строится,31.05.2019,3 кв 2028,25.10.2028,0.16,240.0,...,Есть,Нет,1,4,4,4429,ЮВАО,Люблино,комфорт,NaN
1478,71246,"ЖК ""Гранель Аникеевский""",ООО СЗ ГРАНЕЛЬ ГОРОД,Гранель,Строится,06.04.2026,2 кв 2028,31.12.2028,NaN,NaN,...,Есть,Нет,8,Нет,8,nan,ТАО,Первомайское,бизнес,NaN
1479,54528,"Жилой комплекс ""Кутузовский квартал""",АО СЗ МОНЕТЧИК,ПИК,Сдан,28.09.2023,3 кв 2026,31.07.2026,0.81,107.0,...,Есть,Нет,2,Нет,7,7684,ЗАО,Кунцево,комфорт,NaN
1480,36169,"Жилой район «Южная Битца», Жилой комплекс «Южн...",ООО СЗ ВОСТОК СТОЛИЦЫ,ФСК,Сдан,23.06.2020,4 кв 2021,30.06.2022,0.63,551.0,...,Есть,Нет,13,8,19,4622,Ленинский,Булатниковское,комфорт,NaN
1481,47447,Новые Ватутинки,ООО СЗ СТРОЙКОМ 1,Стройком,Сдан,05.08.2022,3 кв 2025,30.12.2025,0.92,116.0,...,Есть,Нет,21,10,21,6164,НАО,Десеновское,комфорт,NaN

In [23]:
df.to_excel(r'C:\PycharmProjects\ndv_parcing\НашДомРФ\2026-07-27\НашДомРФ_join.xlsx')